// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSfbpQvZL5NOmFXmyR-yvlacN9h0X-_E0',
    appId: '1:826009346463:web:4844c9eb48e7168eca5daa',
    messagingSenderId: '826009346463',
    projectId: 'usuarios-byr-uge',
    authDomain: 'usuarios-byr-uge.firebaseapp.com',
    storageBucket: 'usuarios-byr-uge.appspot.com',
    measurementId: 'G-R87N954S99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIHnwWFpLWPr8AzirUoS5EmKBQHVag7xQ',
    appId: '1:826009346463:android:875cc3efc72dd97eca5daa',
    messagingSenderId: '826009346463',
    projectId: 'usuarios-byr-uge',
    storageBucket: 'usuarios-byr-uge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZokHf7ttwST8aTCrkq-lCTel6zsljM3w',
    appId: '1:826009346463:ios:0efd6c8ceefa01cfca5daa',
    messagingSenderId: '826009346463',
    projectId: 'usuarios-byr-uge',
    storageBucket: 'usuarios-byr-uge.appspot.com',
    iosBundleId: 'com.byr.uge',
  );

}